POST http://localhost:3001/api/sql/parse HTTP/1.1
content-type: application/json

{
    "sql":"CREATE TABLE users (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  username VARCHAR(50) NOT NULL COMMENT 'Login name',
  email VARCHAR(120) NOT NULL,
  age INT DEFAULT 18,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id)
);"
}